'use client'

import { useState, useEffect, useRef } from 'react'
import { getRuntimeTableMetadata, isDatabaseConnected } from '@/lib/queryEngine'

// ── Professional SVG Icons ────────────────────────────────────────────────────
const IC = {
  DB: ({ color = '#ff9900', size = 15 }) => (
    <svg width={size} height={size} viewBox="0 0 20 20" fill="none">
      <ellipse cx="10" cy="5" rx="6.5" ry="2.2" stroke={color} strokeWidth="1.4" />
      <ellipse cx="10" cy="15" rx="6.5" ry="2.2" stroke={color} strokeWidth="1.4" />
      <line x1="3.5" y1="5" x2="3.5" y2="15" stroke={color} strokeWidth="1.4" />
      <line x1="16.5" y1="5" x2="16.5" y2="15" stroke={color} strokeWidth="1.4" />
      <path d="M3.5 10c0 1.2 2.9 2.2 6.5 2.2s6.5-1 6.5-2.2" stroke={color} strokeWidth="1.2" fill="none" />
    </svg>
  ),
  TABLE: ({ color = '#4fc1ff', size = 13 }) => (
    <svg width={size} height={size} viewBox="0 0 16 16" fill="none">
      <rect x="1" y="1" width="14" height="14" rx="1.5" stroke={color} strokeWidth="1.3" />
      <line x1="1" y1="5" x2="15" y2="5" stroke={color} strokeWidth="1" />
      <line x1="6" y1="1" x2="6" y2="15" stroke={color} strokeWidth="1" />
    </svg>
  ),
  VIEW: ({ color = '#9cdcfe', size = 13 }) => (
    <svg width={size} height={size} viewBox="0 0 16 16" fill="none">
      <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8z" stroke={color} strokeWidth="1.2" />
      <circle cx="8" cy="8" r="2.5" stroke={color} strokeWidth="1.2" />
    </svg>
  ),
  SCHEMA: ({ color = '#e8bf6a', size = 13 }) => (
    <svg width={size} height={size} viewBox="0 0 16 16" fill="none">
      <path d="M1 4.5A1.5 1.5 0 0 1 2.5 3h2.764c.577 0 1.09.31 1.55.75H13.5A1.5 1.5 0 0 1 15 5.25v6.25A1.5 1.5 0 0 1 13.5 13h-11A1.5 1.5 0 0 1 1 11.5v-7z" stroke={color} strokeWidth="1.2" />
    </svg>
  ),
  COL: ({ color = '#9cdcfe', size = 11 }) => (
    <svg width={size} height={size} viewBox="0 0 12 12" fill="none">
      <rect x="1" y="2.5" width="10" height="1.5" rx="0.5" fill={color} opacity="0.7" />
      <rect x="1" y="5.5" width="7" height="1.5" rx="0.5" fill={color} opacity="0.5" />
      <rect x="1" y="8.5" width="8.5" height="1.5" rx="0.5" fill={color} opacity="0.4" />
    </svg>
  ),
  KEY: ({ size = 11 }) => (
    <svg width={size} height={size} viewBox="0 0 16 16" fill="#f0c040">
      <path d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8zm4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5z" />
      <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
    </svg>
  ),
  CHEVRON_R: () => <svg width="8" height="8" viewBox="0 0 16 16" fill="currentColor"><path d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" /></svg>,
  CHEVRON_D: () => <svg width="8" height="8" viewBox="0 0 16 16" fill="currentColor"><path d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z" /></svg>,
  REFRESH: () => <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor"><path d="M8 3a5 5 0 1 0 4.546 2.914.5.5 0 0 1 .908-.417A6 6 0 1 1 8 2v1z" /><path d="M8 4.466V.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384L8.41 4.658A.25.25 0 0 1 8 4.466z" /></svg>,
  SEARCH: () => <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor"><path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.099zm-5.242 1.656a5.5 5.5 0 1 1 0-11 5.5 5.5 0 0 1 0 11z" /></svg>,
  CLOSE: () => <svg width="10" height="10" viewBox="0 0 16 16" fill="currentColor"><path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" /></svg>,
}

// ── DDL Generator ─────────────────────────────────────────────────────────────
function generateDDL(table, schemaName) {
  const cols = table.columns.map(col => {
    let line = `  ${col.name.padEnd(28)} ${col.type}`
    if (col.pk || col.nl === 'NN') line += ' NOT NULL'
    return line
  })
  const pks = table.columns.filter(c => c.pk).map(c => c.name)
  if (pks.length) cols.push(`  PRIMARY KEY (${pks.join(', ')})`)
  let ddl = `-- Table: ${schemaName}.${table.name}\n-- Generated by RCR Query Editor\n\nCREATE TABLE ${schemaName}.${table.name} (\n${cols.join(',\n')}\n)`
  if (table.distKey) ddl += `\nDISTKEY (${table.distKey})`
  if (table.sortKey) ddl += `\nSORTKEY (${table.sortKey})`
  ddl += ';'
  return ddl
}

function toGenericColumns(columns = []) {
  return columns.map((column) => {
    if (typeof column === 'object' && column?.name) {
      return { name: column.name, type: column.type || 'STRING', pk: false, nl: 'NULL', cmp: 'none' }
    }
    return { name: String(column), type: 'STRING', pk: false, nl: 'NULL', cmp: 'none' }
  })
}

function buildConnectionsFromRuntime(runtimeMetadata = {}) {
  return Object.entries(runtimeMetadata)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([databaseName, schemas]) => {
      const connected = isDatabaseConnected(databaseName)
      return {
        id: databaseName,
        name: databaseName,
        connected,
        schemas: connected
          ? Object.entries(schemas)
              .sort(([left], [right]) => left.localeCompare(right))
              .map(([schemaName, tables]) => ({
                name: schemaName,
                tables: Object.entries(tables)
                  .sort(([left], [right]) => left.localeCompare(right))
                  .map(([tableName, tableData]) => ({
                    name: tableName,
                    type: tableData.type || 'table',
                    distKey: null,
                    sortKey: null,
                    columns: toGenericColumns(tableData.columns || []),
                  })),
              }))
          : [],
      }
    })
}

// ── Context Menu ──────────────────────────────────────────────────────────────
function CtxMenu({ x, y, items, onClose }) {
  useEffect(() => {
    const h = () => { onClose() }
    document.addEventListener('pointerdown', h)
    return () => document.removeEventListener('pointerdown', h)
  }, [onClose])

  const safeX = Math.min(x, (typeof window !== 'undefined' ? window.innerWidth : 1200) - 210)
  const safeY = Math.min(y, (typeof window !== 'undefined' ? window.innerHeight : 800) - items.length * 36 - 16)

  return (
    <div style={{ position: 'fixed', left: safeX, top: safeY, zIndex: 2000, background: 'var(--bg-panel)', border: '1px solid var(--border)', borderRadius: 8, boxShadow: '0 8px 32px rgba(0,0,0,0.55)', minWidth: 200, padding: '4px 0' }}
      onPointerDown={e => e.stopPropagation()}>
      {items.map((item, i) => item === '---'
        ? <div key={i} style={{ height: 1, background: 'var(--border)', margin: '3px 8px' }} />
        : (
          <div key={i}
            onPointerDown={(e) => { e.preventDefault(); e.stopPropagation(); item.action(); onClose() }}
            style={{ padding: '7px 14px', cursor: 'pointer', fontSize: 12, color: item.danger ? '#f85149' : 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 8 }}
            onMouseEnter={e => e.currentTarget.style.background = 'var(--bg-hover)'}
            onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
            {item.icon && <span style={{ display: 'flex', alignItems: 'center', opacity: 0.8, flexShrink: 0 }}>{item.icon}</span>}
            {item.label}
          </div>
        )
      )}
    </div>
  )
}

// ── Tree Node ─────────────────────────────────────────────────────────────────
function TreeNode({ label, icon, children, depth = 0, defaultOpen = false, forceOpen = false, onDoubleClick, onContextMenu, badge, active, onSelect, statusIndicator }) {
  const [open, setOpen] = useState(defaultOpen)
  const hasChildren = children && children.length > 0
  const prevForceOpenRef = useRef(false)

  useEffect(() => {
    if (forceOpen) {
      prevForceOpenRef.current = true
      setOpen(true)
    } else if (prevForceOpenRef.current) {
      prevForceOpenRef.current = false
      setOpen(false)
    }
  }, [forceOpen])

  const isOpen = hasChildren && (open || forceOpen)

  return (
    <div>
      <div
        className={`tree-item${active ? ' active' : ''}`}
        style={{ paddingLeft: `${6 + depth * 13}px` }}
        onClick={() => { setOpen(o => !o); onSelect && onSelect() }}
        onDoubleClick={onDoubleClick}
        onMouseDown={(e) => {
          if (e.button === 0 && e.ctrlKey && onContextMenu) onContextMenu(e)
        }}
        onContextMenu={onContextMenu}
      >
        <span style={{ color: '#6e7681', marginRight: 2, width: 11, display: 'inline-flex', alignItems: 'center', flexShrink: 0 }}>
          {hasChildren ? (isOpen ? <IC.CHEVRON_D /> : <IC.CHEVRON_R />) : <span style={{ width: 9 }} />}
        </span>
        <span style={{ marginRight: 5, display: 'inline-flex', alignItems: 'center', flexShrink: 0 }}>{icon}</span>
        <span style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', color: 'var(--text-primary)', fontSize: 12 }}>{label}</span>
        {statusIndicator}
        {badge !== undefined && badge !== null && (
          <span style={{ fontSize: 10, color: '#6e7681', marginLeft: 4, background: 'var(--bg-tertiary)', padding: '0 5px', borderRadius: 8, flexShrink: 0, lineHeight: '16px' }}>{badge}</span>
        )}
      </div>
      {isOpen && <div>{children}</div>}
    </div>
  )
}

// ── Table Detail Panel ────────────────────────────────────────────────────────
function TableDetailPanel({ table, onClose }) {
  if (!table) return null
  return (
    <div style={{ borderTop: '1px solid var(--border)', background: 'var(--bg-panel)', flexShrink: 0, maxHeight: 240, display: 'flex', flexDirection: 'column' }}>
      <div style={{ display: 'flex', alignItems: 'center', padding: '7px 10px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <span style={{ marginRight: 6, display: 'inline-flex' }}>{table.type === 'view' ? <IC.VIEW /> : <IC.TABLE />}</span>
        <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-primary)', flex: 1 }}>{table.name}</span>
        <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#6e7681', padding: 2, display: 'flex' }}><IC.CLOSE /></button>
      </div>
      {(table.distKey || table.sortKey) && (
        <div style={{ padding: '5px 10px', borderBottom: '1px solid var(--border)', fontSize: 11, flexShrink: 0 }}>
          {table.distKey && <div style={{ marginBottom: 2 }}><span style={{ color: '#6e7681' }}>DISTKEY: </span><span style={{ color: '#79c0ff' }}>{table.distKey}</span></div>}
          {table.sortKey && <div><span style={{ color: '#6e7681' }}>SORTKEY: </span><span style={{ color: '#79c0ff' }}>{table.sortKey}</span></div>}
        </div>
      )}
      <div style={{ overflowY: 'auto', flex: 1 }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
          <thead>
            <tr>{['Field', 'Type', 'NL', 'CMP'].map(h => (
              <th key={h} style={{ padding: '4px 8px', textAlign: 'left', color: '#6e7681', borderBottom: '1px solid var(--border)', fontWeight: 600, background: 'var(--bg-secondary)', position: 'sticky', top: 0 }}>{h}</th>
            ))}</tr>
          </thead>
          <tbody>
            {table.columns.map((col, i) => (
              <tr key={i} style={{ borderBottom: '1px solid var(--border-light, #21262d)' }}>
                <td style={{ padding: '4px 8px' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                    {col.pk ? <IC.KEY /> : <IC.COL />}
                    <span style={{ color: col.pk ? '#f0c040' : 'var(--text-primary)' }}>{col.name}</span>
                  </div>
                </td>
                <td style={{ padding: '4px 8px', color: 'var(--text-secondary)' }}>{col.type}</td>
                <td style={{ padding: '4px 8px', color: col.nl === 'NN' ? '#f85149' : '#6e7681' }}>{col.nl}</td>
                <td style={{ padding: '4px 8px', color: '#6e7681' }}>{col.cmp}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// ── Main Sidebar ──────────────────────────────────────────────────────────────

export default function Sidebar({ onTableDoubleClick, onShowSQL, onCreateAction, onLoadData, onDBConnect, onDBDisconnect, width, onCollapse, refreshKey = 0, theme = 'dark' }) {
  const [search, setSearch] = useState('')
  const [activeNode, setActiveNode] = useState(null)
  const [selectedTable, setSelectedTable] = useState(null)
  const [refreshing, setRefreshing] = useState(false)
  const [showCreateMenu, setShowCreateMenu] = useState(false)
  const [ctxMenu, setCtxMenu] = useState(null)
  const [runtimeMetadata, setRuntimeMetadata] = useState({})

  const connections = buildConnectionsFromRuntime(runtimeMetadata)
  const searchTerm = search.trim().toLowerCase()

  const handleRefresh = () => {
    setRefreshing(true)
    setRuntimeMetadata(getRuntimeTableMetadata())
    setTimeout(() => setRefreshing(false), 800)
  }

  const handleTableSelect = (table, schemaName) => {
    setActiveNode(`${schemaName}-${table.name}`)
    setSelectedTable({ ...table, schemaName })
  }

  const openCtxMenu = (e, type, data) => {
    e.preventDefault(); e.stopPropagation()
    setCtxMenu({ x: e.clientX, y: e.clientY, type, data })
  }

  useEffect(() => {
    setRuntimeMetadata(getRuntimeTableMetadata())
  }, [refreshKey])

  const CREATE_ITEMS = ['New Query', 'New Notebook', 'New View', 'New Table', 'New Schema']

  return (
    <div style={{ width, minWidth: 200, maxWidth: 500, display: 'flex', flexDirection: 'column', background: 'var(--bg-secondary)', borderRight: '1px solid var(--border)', height: '100%', position: 'relative' }}>

      {/* Header */}
      <div style={{ padding: '8px 10px 6px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}>
          <img src={theme === 'dark' ? '/white_logo_alrajhi.png' : '/alrajhi_logo.png'} alt="Al Rajhi" style={{ height: 26, objectFit: 'contain', flexShrink: 0 }} onError={e => { e.target.style.display = 'none' }} />
          <span style={{ flex: 1, fontSize: 11, fontWeight: 700, color: 'var(--text-primary)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>RCR Query Editor</span>
          <button onClick={onCollapse} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', padding: '2px 4px', display: 'flex' }} title="Collapse">
            <svg width="12" height="12" viewBox="0 0 16 16" fill="currentColor"><path d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" /><path d="M7.354 1.646a.5.5 0 0 1 0 .708L1.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z" /></svg>
          </button>
        </div>

        {/* Create + Load */}
        <div style={{ display: 'flex', gap: 5, marginBottom: 8, position: 'relative' }}>
          <button className="btn-primary" style={{ flex: 1, justifyContent: 'center', padding: '5px 8px', fontSize: 11 }}
            onClick={() => setShowCreateMenu(s => !s)}>
            <svg width="10" height="10" viewBox="0 0 16 16" fill="currentColor" style={{ marginRight: 4 }}><path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" /></svg>
            Create ▾
          </button>
          {showCreateMenu && (
            <>
              <div style={{ position: 'fixed', inset: 0, zIndex: 98 }} onClick={() => setShowCreateMenu(false)} />
              <div style={{ position: 'absolute', top: '100%', left: 0, zIndex: 99, background: 'var(--bg-panel)', border: '1px solid var(--border)', borderRadius: 7, boxShadow: '0 8px 24px rgba(0,0,0,0.4)', minWidth: 160, marginTop: 3, padding: '4px 0' }}>
                {CREATE_ITEMS.map(label => (
                  <div key={label}
                    onClick={() => { onCreateAction && onCreateAction(label); setShowCreateMenu(false) }}
                    style={{ padding: '7px 14px', cursor: 'pointer', fontSize: 12, color: 'var(--text-primary)' }}
                    onMouseEnter={e => e.currentTarget.style.background = 'var(--bg-hover)'}
                    onMouseLeave={e => e.currentTarget.style.background = 'transparent'}>
                    {label}
                  </div>
                ))}
              </div>
            </>
          )}
          <button className="btn-secondary" style={{ flex: 1, justifyContent: 'center', padding: '5px 8px', fontSize: 11 }}
            onClick={() => onLoadData && onLoadData()}>
            <svg width="10" height="10" viewBox="0 0 16 16" fill="currentColor" style={{ marginRight: 4 }}><path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z" /><path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z" /></svg>
            Load data
          </button>
        </div>

        {/* Search + Refresh */}
        <div style={{ display: 'flex', gap: 4 }}>
          <div style={{ position: 'relative', flex: 1 }}>
            <span style={{ position: 'absolute', left: 7, top: '50%', transform: 'translateY(-50%)', color: '#6e7681', pointerEvents: 'none' }}><IC.SEARCH /></span>
            <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Filter resources"
              style={{ width: '100%', background: 'var(--bg-tertiary)', border: '1px solid var(--border)', borderRadius: 4, padding: '5px 8px 5px 26px', fontSize: 12, color: 'var(--text-primary)', outline: 'none', boxSizing: 'border-box' }} />
          </div>
          <button onClick={handleRefresh} style={{ background: 'none', border: '1px solid var(--border)', borderRadius: 4, cursor: 'pointer', color: '#6e7681', padding: '0 7px', display: 'flex', alignItems: 'center' }}>
            <span style={{ display: 'inline-block', animation: refreshing ? 'rcr-spin 0.8s linear infinite' : 'none' }}><IC.REFRESH /></span>
          </button>
        </div>
      </div>

      {/* Tree */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '4px 0' }}>
        {connections.map(conn => {
          const schemaWithMatches = conn.schemas.map(schema => {
            const matchingTables = schema.tables.filter(t => t.type === 'table' && (!searchTerm || t.name.toLowerCase().includes(searchTerm)))
            const matchingViews = schema.tables.filter(t => t.type === 'view' && (!searchTerm || t.name.toLowerCase().includes(searchTerm)))
            return {
              ...schema,
              matchingTables,
              matchingViews,
              hasMatch: matchingTables.length > 0 || matchingViews.length > 0,
            }
          })

          const connectionHasMatch = schemaWithMatches.some(schema => schema.hasMatch)
          const forceOpenConnection = Boolean(searchTerm) && conn.connected && connectionHasMatch

          return (
            <TreeNode key={conn.id} label={conn.name}
              icon={<IC.DB color="#ff9900" />}
              statusIndicator={<span title={conn.connected ? 'Connected' : 'Disconnected'} style={{ width: 8, height: 8, borderRadius: '50%', background: conn.connected ? '#3fb950' : '#6e7681', boxShadow: conn.connected ? '0 0 6px rgba(63,185,80,0.9)' : 'none', marginRight: 6, flexShrink: 0 }} />}
              depth={0} active={activeNode === conn.id}
              forceOpen={forceOpenConnection}
              onSelect={() => setActiveNode(conn.id)}
              onContextMenu={e => openCtxMenu(e, 'db', conn)}>
              {schemaWithMatches.map(schema => (
                <TreeNode key={schema.name} label={schema.name} icon={<IC.SCHEMA />} depth={1}
                  active={activeNode === `${conn.id}-${schema.name}`} badge={schema.tables.length}
                  forceOpen={Boolean(searchTerm) && schema.hasMatch}
                  onSelect={() => setActiveNode(`${conn.id}-${schema.name}`)}>
                  <TreeNode label="Tables" depth={2} icon={<IC.TABLE />}
                    badge={schema.tables.filter(t => t.type === 'table').length}
                    forceOpen={Boolean(searchTerm) && schema.matchingTables.length > 0}>
                    {schema.matchingTables.map(table => (
                      <TreeNode key={table.name} label={table.name} depth={3} icon={<IC.TABLE />}
                        active={activeNode === `${schema.name}-${table.name}`}
                        onSelect={() => handleTableSelect(table, schema.name)}
                        onDoubleClick={() => { handleTableSelect(table, schema.name); onTableDoubleClick && onTableDoubleClick(table.name, schema.name) }}
                        onContextMenu={e => openCtxMenu(e, 'table', { table, schemaName: schema.name })}>
                        {table.columns.map(col => (
                          <div key={col.name} className="tree-item" style={{ paddingLeft: `${6 + 4 * 13}px`, fontSize: 11 }}>
                            <span style={{ width: 11, display: 'inline-flex', marginRight: 2, flexShrink: 0 }} />
                            <span style={{ marginRight: 5, display: 'inline-flex', flexShrink: 0 }}>{col.pk ? <IC.KEY /> : <IC.COL />}</span>
                            <span style={{ flex: 1, color: col.pk ? '#f0c040' : 'var(--text-primary)' }}>{col.name}</span>
                            <span style={{ color: '#6e7681', fontSize: 10, marginRight: 6 }}>{col.type}</span>
                          </div>
                        ))}
                      </TreeNode>
                    ))}
                  </TreeNode>
                  {schema.matchingViews.length > 0 && (
                    <TreeNode label="Views" depth={2} icon={<IC.VIEW />}
                      badge={schema.tables.filter(t => t.type === 'view').length}
                      forceOpen={Boolean(searchTerm) && schema.matchingViews.length > 0}>
                      {schema.matchingViews.map(view => (
                        <TreeNode key={view.name} label={view.name} depth={3} icon={<IC.VIEW />}
                          active={activeNode === `${schema.name}-${view.name}`}
                          onSelect={() => handleTableSelect(view, schema.name)}
                          onDoubleClick={() => { handleTableSelect(view, schema.name); onTableDoubleClick && onTableDoubleClick(view.name, schema.name) }}
                          onContextMenu={e => openCtxMenu(e, 'table', { table: view, schemaName: schema.name })}>
                          {view.columns.map(col => (
                            <div key={col.name} className="tree-item" style={{ paddingLeft: `${6 + 4 * 13}px`, fontSize: 11 }}>
                              <span style={{ width: 11, display: 'inline-flex', marginRight: 2, flexShrink: 0 }} />
                              <span style={{ marginRight: 5, display: 'inline-flex', flexShrink: 0 }}><IC.COL /></span>
                              <span style={{ flex: 1, color: 'var(--text-primary)' }}>{col.name}</span>
                              <span style={{ color: '#6e7681', fontSize: 10, marginRight: 6 }}>{col.type}</span>
                            </div>
                          ))}
                        </TreeNode>
                      ))}
                    </TreeNode>
                  )}
                </TreeNode>
              ))}
            </TreeNode>
          )
        })}
      </div>

      {/* Table detail panel */}
      {selectedTable && <TableDetailPanel table={selectedTable} onClose={() => setSelectedTable(null)} />}

      {/* DB right-click menu */}
      {ctxMenu?.type === 'db' && (
        <CtxMenu x={ctxMenu.x} y={ctxMenu.y} onClose={() => setCtxMenu(null)} items={[
          {
            label: 'Connect',
            icon: <svg width="11" height="11" viewBox="0 0 16 16" fill="currentColor"><circle cx="8" cy="8" r="2" fill="currentColor"/><path d="M1.5 8a6.5 6.5 0 1 1 13 0 6.5 6.5 0 0 1-13 0z" stroke="currentColor" strokeWidth="1" fill="none"/></svg>,
            action: () => onDBConnect && onDBConnect(ctxMenu.data.id || ctxMenu.data.name)
          },
          {
            label: 'Disconnect',
            icon: <svg width="11" height="11" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V2a.5.5 0 0 1 .5-.5z"/><path d="M3.757 3.05a.5.5 0 0 1 .707 0l.758.757a.5.5 0 0 1-.707.707l-.758-.757a.5.5 0 0 1 0-.707zm8.486 0a.5.5 0 0 1 0 .707l-.758.757a.5.5 0 1 1-.707-.707l.758-.757a.5.5 0 0 1 .707 0z"/><path d="M8 7a5 5 0 1 0 5 5 .5.5 0 0 1 1 0A6 6 0 1 1 2 12a.5.5 0 0 1 1 0 5 5 0 0 0 5-5z"/></svg>,
            action: () => onDBDisconnect && onDBDisconnect(ctxMenu.data.id || ctxMenu.data.name)
          },
          '---',
          {
            label: 'Copy Database Name',
            icon: <svg width="11" height="11" viewBox="0 0 16 16" fill="currentColor"><path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/></svg>,
            action: () => navigator.clipboard?.writeText(ctxMenu.data.id || '')
          },
          { label: 'Refresh', icon: <IC.REFRESH />, action: handleRefresh },
        ]} />
      )}

      {/* Table right-click menu */}
      {ctxMenu?.type === 'table' && (
        <CtxMenu x={ctxMenu.x} y={ctxMenu.y} onClose={() => setCtxMenu(null)} items={[
          {
            label: 'Preview (SELECT * LIMIT 100)',
            icon: <svg width="11" height="11" viewBox="0 0 16 16" fill="currentColor"><path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/><path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8z"/></svg>,
            action: () => onTableDoubleClick && onTableDoubleClick(ctxMenu.data.table.name, ctxMenu.data.schemaName)
          },
          {
            label: 'Show SQL (DDL)',
            icon: <svg width="11" height="11" viewBox="0 0 16 16" fill="#79c0ff"><path d="M1.5 0h-1v16h1V0zm13 0v16h1V0h-1zM3.646 5.354a.5.5 0 0 0-.708.708L5.293 8l-2.355 1.938a.5.5 0 0 0 .708.708L6.5 8.414V8L3.646 5.354zm5.708 0L12.5 8l-3.146 2.646a.5.5 0 0 1-.708-.708L10.707 8 8.646 6.062a.5.5 0 0 1 .708-.708z" /></svg>,
            action: () => {
              const { table, schemaName } = ctxMenu.data
              onShowSQL && onShowSQL(table.name, generateDDL(table, schemaName))
            }
          },
          '---',
          {
            label: 'Copy Table Name',
            icon: <svg width="11" height="11" viewBox="0 0 16 16" fill="currentColor"><path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/></svg>,
            action: () => navigator.clipboard?.writeText(ctxMenu.data.table.name)
          },
          {
            label: 'Copy SELECT Statement',
            icon: <svg width="11" height="11" viewBox="0 0 16 16" fill="currentColor"><path d="M1.5 0h-1v16h1V0zm13 0v16h1V0h-1z"/></svg>,
            action: () => {
              const { table, schemaName } = ctxMenu.data
              const prefix = schemaName !== 'public' ? schemaName + '.' : ''
              const cols = table.columns.map(c => `  ${c.name}`).join(',\n')
              navigator.clipboard?.writeText(`SELECT\n${cols}\nFROM ${prefix}${table.name}\nLIMIT 100;`)
            }
          },
        ]} />
      )}

      <style jsx global>{`
        @keyframes rcr-spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </div>
  )
}
